apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ccore-ai-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/laurisneimanis/ccore-ai-demo-frontend:latest
        env:
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: BACKEND_URL
          value: "http://backend:8000"
        ports:
        - containerPort: 8501
