name: Terraform CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.0"

      - name: Provide default tfvars for CI
        working-directory: terraform/envs/dev
        run: cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init -backend=false -input=false

      - name: Terraform Format (repo-wide)
        run: terraform fmt -check -recursive terraform/

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.60.0
      
      - name: Run TFLint (repo-wide)
        run: tflint --init && tflint
        working-directory: terraform

      - name: Run tfsec (custom, with config)
        run: |
          curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.14/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/tfsec
          tfsec ./terraform --config-file .tfsec.yaml

      - name: Terraform Validate
        working-directory: terraform/envs/dev
        run: terraform validate
